### ISSUE TITLE
GDPR/AIL

### ISSUE THREAD

**Issue by ancormack** [CIRCL/compliance#3]
Good stuff, thanks. 

A couple of things that strengthen your argument. First, the Legitimate Interests basis allows you to include the Interests of third parties, too, so if you plan to notify organisations or individuals about leaks of their information then that strengthens the argument for processing the personal data in the first place. See, for example, p.28 of Article 29 Opinion 06/2014 on Legitimate Interests and section 4.1.1 of my paper on [Incident Response and the GDPR](https://script-ed.org/article/incident-response-protecting-individual-rights-under-the-general-data-protection-regulation/)

There's also an argument, I think, that planning to notify individuals (either directly or via relevant third parties) of leaks supports the Article 14 (qualified) requirement to notify. Again that should make the argument in favour of processing stronger.

Andrew

**Comment by adulau** [comment]
@ancormack Thank you very much for the feedback.  This is great. We will include your input in the next revision.

**Comment by ancormack** [comment]
You’re welcome. My first successful use of Github ;-)

Andrew
—
Andrew Cormack
Chief Regulatory Adviser
Jisc

On 21 Jun 2018, at 12:57, Alexandre Dulaunoy <notifications@github.com<mailto:notifications@github.com>> wrote:


@ancormack<https://github.com/ancormack> Thank you very much for the feedback. This is great. We will include your input in the next revision.

**Comment by adulau** [comment]
Thank you for the contribution. The reference and argumentation have added to the latest version.
